# Generated by Django 3.0.5 on 2023-10-30 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExtra',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('authapp.user',),
        ),
    ]
